AWSTemplateFormatVersion: '2010-09-09'
Description: Integrtion Lambda Template
Parameters:
  Vpc:
    Type: String
    Description: The VPC that it runs in (  'qa' or 'prod')
    Default: qa
    AllowedValues:
      - qa
      - prod
  Name:
    Type: String
    Description: Unique Name of the Lambda to be deployed
  Version:
    Type: String
    Description: StackVersion

Resources:
  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Join ['-',[ !Ref Vpc,"fathom-integration"]]
        S3Key: !Join
          - ''
          - - lambda/
            - !Ref Name
            - '-'
            - !Ref 'Version'
            - .zip
      Description: !Join [' ',[ !Ref Vpc ,!Ref Name, "lambda"]]
      Environment:
        Variables:
          Environment: !Ref Vpc
          Version: !Ref 'Version'
          Dbhost:
            Fn::ImportValue: !Join [':',[!Ref Vpc,"aurora-db-endpoint-address"]]
      FunctionName: !Join ['-',[ !Ref Vpc ,!Ref Name, "lambda"]]
      Handler: !Join ['.',[!Ref Name, "lambda_handler"]]
      MemorySize: 128
      Role: !GetAtt 'LambdaRole.Arn'
      Runtime: python3.6
      TracingConfig:
        Mode: Active
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Join [':',[!Ref Vpc,"fathom-all-port-internal-security-group"]]
        SubnetIds:
          Fn::Split:
          - ","
          - Fn::ImportValue: !Join [':',[!Ref "Vpc", "private-subnets"]]
      Timeout: 300
      Tags:
        - Key: version
          Value: !Ref 'Version'

  LambdaAlias:
    Type: AWS::Lambda::Alias
    Properties:
      Name: !Join ['-',[ !Ref Vpc ,!Ref Name, "Lambda"]]
      Description: !Join [' ',[ !Ref Vpc ,!Ref Name, "lambda"]]
      FunctionName: !Ref 'Lambda'
      FunctionVersion: "$LATEST"


  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName:  !Join ['-',[ !Ref Vpc ,!Ref Name, "lambda-policy"]]
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - !Join ['-',[ "arn:aws:s3:::", !Ref Vpc,"fathom-integration"]]
              - Sid: ec2
                Effect: Allow
                Action:
                  - ses:*
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - ec2:*
                Resource: '*'
              - Sid: xray
                Effect: Allow
                Action:
                  - xray:*
                Resource: '*'
              - Sid: sqs
                Effect: Allow
                Action:
                  - sqs:*
                Resource: '*'


Outputs:
  Lambda:
    Description: "lambda arn"
    Value: !GetAtt Lambda.Arn
    Export:
      Name: !Join [':',[ !Ref Vpc ,!Ref Name, "lambda"]]
